[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
glob = "0.3.3"
serde = { workspace = true, features = ["derive"] }
toml = "0.9.12"
walkdir = "2.5.0"
