//! Minimal coverage tests for the workspace-hack crate.
//!
//! The workspace-hack crate is auto-generated by `cargo hakari` to unify
//! dependency features across the workspace. It contains no public API,
//! but these tests verify it compiles and links correctly.

type TestResult = Result<(), Box<dyn std::error::Error>>;

#[test]
fn workspace_hack_crate_compiles() -> TestResult {
    // The workspace-hack crate has no public API; this test simply
    // verifies that the crate and all its unified dependencies compile.
    Ok(())
}
